name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Visual Studio environment
      shell: pwsh
      run: |
        # Find Visual Studio installation path
        $vswherePath = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
        $vsInstallPath = & $vswherePath -latest -products * -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath

        if (-not $vsInstallPath) {
          Write-Error "Visual Studio not found."
          exit 1
        }

        # Set up environment variables
        $vsVarsPath = "$vsInstallPath\VC\Auxiliary\Build\vcvars64.bat"
        Write-Host "Visual Studio found at: $vsInstallPath"

        # Invoke vcvars64.bat and propagate environment variables to subsequent commands
        cmd /c """$vsVarsPath"" && set"

    - name: Build with MSVC
      shell: cmd
      run: |
        # Run nmake to build the project
        call nmake -f makefile.msvc

    - name: Archive build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: webcam

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.sha }}
        release_name: Release ${{ github.sha }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: webcam
        asset_name: webcam.exe
        asset_content_type: application/octet-stream
